name: env_juanma
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - imbalanced-learn
  - lightgbm
  - matplotlib
  - scikit-learn
  - seaborn
  - pip:
      - numpy
      - pandas
      - tensorflow
      - xgboost
      - protobuf
